import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./home/navbar/page";
import Sidebar from "./home/sidebar/page";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="main-container flex flex-row">
          <Sidebar />
          <div className="main-content w-full flex flex-col  relative">
            <NavBar />
            <div className="mt-16">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
